name: SumberBaru
description: "Absensi Sumber Baru ban."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  onesignal_flutter: ^5.4.1
  geolocator: ^14.0.2
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.0.7
  file_picker: ^10.3.10
  flutter_cached_pdfview: ^0.4.2
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.0.0
  open_file: ^3.3.0
  shared_preferences: ^2.2.2

flutter_icons:
  android: true
  ios: false
  image_path: "lib/assets/sbb.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter:
  assets:
    - lib/assets/sbb.png
    - lib/assets/Gemini_Generated_Image_7461ma7461ma7461.png
    - lib/assets/spooring-berkala.jpg

  uses-material-design: true